# Generated by Django 3.1.6 on 2021-06-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210613_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createtask',
            old_name='text',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='createtask',
            old_name='file',
            new_name='upload_file',
        ),
    ]
